### ISSUE TITLE
Webjob  returning exception 

### ISSUE THREAD

**Issue by s3banerjee** [Microsoft/peek#36]
Hi, 

This is linked to issue 33 , where we are in CSP partner is **Cloud re seller**. 

so in swagger we are getting the Response 

Response code 200 

/api/cspbilling : - Returning back response 200 , but nothing in response body
/api/cspbilling/currentmonth : - Returning back response 200 , but nothing in response body
/api/cspusage :- Response 500.
/api/userbilling :- Response 500.

[Error_details.docx](https://github.com/Microsoft/peek/files/792107/Error_details.docx)

 

https://online.swagger.io/validator/debug?url=https://deployment-demo-app-service.azurewebsites.net:443/swagger/docs/v1

{} 

is showing valid URL 

Further moving on Section 4 (Web jobs) 

While running the Webjobs , it is giving me back 

 

[02/21/2017 20:59:18 > 622409: SYS INFO] Status changed to Starting
[02/21/2017 20:59:18 > 622409: SYS WARN] 'Always On' doesn't appear to be enabled for this Web App. To ensure your continuous job doesn't stop running when the SCM host is idle for too long, consider enabling 'Always On' in the configuration settings for your Web App. Note: 'Always On' is available only in Basic, Standard and Premium modes.

> 

[02/21/2017 22:03:58 > 622409: INFO] 
[02/21/2017 22:03:58 > 622409: INFO] Error encountered: 
[02/21/2017 22:03:58 > 622409: INFO] One or more errors occurred.
[02/21/2017 22:03:58 > 622409: INFO] InnerException :
[02/21/2017 22:03:58 > 622409: INFO] Exception of type 'Microsoft.Rest.HttpOperationException`1[System.Object]' was thrown.
[02/21/2017 22:03:58 > 622409: INFO] StackTrace :
[02/21/2017 22:03:58 > 622409: INFO]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[02/21/2017 22:03:58 > 622409: INFO]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[02/21/2017 22:03:58 > 622409: INFO]    at System.Threading.Tasks.Task`1.get_Result()
[02/21/2017 22:03:58 > 622409: INFO]    at BillingWebJob.Helpers.CspDataHelper.StartCspRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri)
[02/21/2017 22:03:58 > 622409: INFO]    at BillingWebJob.Program.CronJob(TimerInfo timer) 
[02/21/2017 22:03:58 > 622409: INFO] 
[02/21/2017 22:03:58 > 622409: INFO] Adding audit information in AuditData table..
[02/21/2017 22:03:58 > 622409: INFO] 
[02/21/2017 22:04:05 > 622409: INFO] 
[02/21/2017 22:04:05 > 622409: INFO] Operation complete. Exiting this run.
[02/21/2017 22:04:05 > 622409: INFO] 
[02/21/2017 22:04:05 > 622409: INFO] Executed: 'Program.CronJob' (Succeeded)
[02/21/2017 22:04:05 > 622409: INFO] Job host started

**Comment by UtkarshVIT** [comment]
Hi
Have you built using the latest version? We have merged the solution given in [issue33 ](https://github.com/Microsoft/peek/issues/33)to the master branch.
In case the error exists despite the latest fix can you share the details of the audit table?

**Comment by s3banerjee** [comment]
Hi Utkarsh, 

Thanks for coming back , yes, i've taken the latest merge (BillingDataApi\Controllers\CspUsageController.cs)  from issue 33 , still an issue.

The below is taken from Auditdata table...

One or more errors occurred.
InnerException :
Exception of type 'Microsoft.Rest.HttpOperationException`1[System.Object]' was thrown.
StackTrace :
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BillingWebJob.Helpers.CspDataHelper.StartCspRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri)
   at BillingWebJob.Program.CronJob(TimerInfo timer)


Thanks,

Saurabh

**Comment by jsoareshot** [comment]
Hello, I have the same issue:

This is the result of my Audit table.

5	2017-03-03 08:02:13.580	0	NULL	-1	One or more errors occurred.
InnerException :
Exception of type 'Microsoft.Rest.HttpOperationException`1[System.Object]' was thrown.
StackTrace :
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BillingWebJob.Helpers.CspDataHelper.StartCspRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri) in C:\peek-master\AzureBillingAnalytics\BillingWebJob\Helpers\CspDataHelper.cs:line 530
   at BillingWebJob.Program.CronJob(TimerInfo timer) in C:\peek-master\AzureBillingAnalytics\BillingWebJob\Program.cs:line 122	csp

thank you
jpsoares

**Comment by CloudCrusader** [comment]
Hi,
in my case all API calls seem to go fine, except the one for cspusage, this one throws me a 500
Webjob does a good job importing to SQL, except for the CSP part, here it times out (even changed mine to 60 minutes)
One or more errors occurred.
InnerException :
Exception of type 'Microsoft.Rest.HttpOperationException`1[System.Object]' was thrown.
StackTrace :
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BillingWebJob.Helpers.CspDataHelper.StartCspRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri)
   at BillingWebJob.Program.CronJob(TimerInfo timer)

**Comment by s3banerjee** [comment]
Hi , 

Previously webapi which was returning 200 Response code and nothing in Response body , now we are getting back 200 Response code and data in Response body , reason it was not working previously is that we have used the CSP data having sandbox (dummy data)  and no trust relationship exists. But after we have used actual data and trust relationship exists , we are populated with data in our database. 

Thanks,

**Comment by jasperkraak** [comment]
Hi,
Same issue here, CSP only. Swagger results are all fine except for CSPUsage. This error probably also prevents the WebJob for completing without error? So no data in Databse.

Error in dbo.AuditData:
One or more errors occurred.
InnerException :
Exception of type 'Microsoft.Rest.HttpOperationException`1[System.Object]' was thrown.
StackTrace :
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BillingWebJob.Helpers.CspDataHelper.StartCspRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri)
   at BillingWebJob.Program.CronJob(TimerInfo timer)

Same Error in WebJob Logs:
[03/18/2017 22:24:56 > 8178b3: INFO] Error encountered: 
[03/18/2017 22:24:56 > 8178b3: INFO] One or more errors occurred.
[03/18/2017 22:24:56 > 8178b3: INFO] InnerException :
[03/18/2017 22:24:56 > 8178b3: INFO] Exception of type 'Microsoft.Rest.HttpOperationException`1[System.Object]' was thrown.
[03/18/2017 22:24:56 > 8178b3: INFO] StackTrace :
[03/18/2017 22:24:56 > 8178b3: INFO]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[03/18/2017 22:24:56 > 8178b3: INFO]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[03/18/2017 22:24:56 > 8178b3: INFO]    at System.Threading.Tasks.Task`1.get_Result()
[03/18/2017 22:24:56 > 8178b3: INFO]    at BillingWebJob.Helpers.CspDataHelper.StartCspRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri)
[03/18/2017 22:24:56 > 8178b3: INFO]    at BillingWebJob.Program.CronJob(TimerInfo timer) 
[03/18/2017 22:24:56 > 8178b3: INFO] 
[03/18/2017 22:24:56 > 8178b3: INFO] Adding audit information in AuditData table..

I noticed in Swagger/cspusage in the "Model";
"BillingStartDate": "2017-03-18T22:14:18.941Z",
"BillingEndDate": "2017-03-18T22:14:18.941Z"
 ...which seams a bit weird?

I started experimenting with peek just 2 days ago, so I have the most recent versions. And I really like what this should be capable of for ourselves and our Customers. So thanks for the great job!

Getting some data in the SQL Database would be nice though, so I can explore the PowerBI thingies.

Thanks. Jasper

**Comment by UtkarshVIT** [comment]
Hi all
Can you ensure that your APIs are accessed as https and have mentioned https in the app.config file on web job 

    
    

    
    <add key="WebApiUrl" value="**https**://yourdomain.azurewebsites.net/" />

**Comment by jasperkraak** [comment]
Hi,

Yes, the URL of my Web API is accessed as https in the app.config file. Also, browsing the Web App and Webjobs and Swagger is on https.

**Comment by UtkarshVIT** [comment]
@jasperkraak Can you share the response of cspusage API call?

**Comment by jasperkraak** [comment]
![2017-03-23_7-00-28](https://cloud.githubusercontent.com/assets/15181202/24244725/7adce688-0f96-11e7-99f3-a731a51a91f7.jpg)

**Comment by UtkarshVIT** [comment]
It might be a timeout error. We have made the usage API asynchronous in one of the branches([here](https://github.com/Microsoft/peek/tree/CSPUsageAsync)). Can you try that and see if it is working?

**Comment by jasperkraak** [comment]
Nope, no different outcomes.....

**Comment by UtkarshVIT** [comment]
Can you check the inner/outer exception and share the messages of the exception?

**Comment by jasperkraak** [comment]
Hi, where can i find more than I already posted? I enabled logging and stuff, I see no more information than I already put in my first post.
Please advise. Tnx.

**Comment by jasperkraak** [comment]
Hi Again,
There is something wrong with my CSP Tenant, we had problems with some other tools as well. I tried PEEK in one of our other CSP Tenants and it works smoothly.

**Comment by UtkarshVIT** [comment]
All right! Please keep us updated with your findings.

**Comment by CloudCrusader** [comment]
@jasperkraak, the Peek solution reads out CSP platform API and hence all tenants that are managed by it. I don't see how you can link it to tenants. For me the problem still exists.

**Comment by jasperkraak** [comment]
@CloudCrusader Sorry for the confusion, we are CSP in multiple Territories so we have multiple Partner Center environments. Each with their own AzureAD and API settings. 
Just one of them is not working with PEEK, 3 others are fine, one has no Azure Subscriptions in it yet.

**Comment by CloudCrusader** [comment]
@jasperkraak. thanks for the update. where you able to pinpoint the issue in the faulting Partner Center?

**Comment by jasperkraak** [comment]
I submitted a Support Request with them. Just replied to their 1st answer where they did not get the issue :-) right the 1st time. I'll keep you posted.

**Comment by CloudCrusader** [comment]
thanks, much appriciated ;)

**Comment by ssugar** [comment]
I've started to see a similar error.  It seems like this occurs when I allow the job to run scheduled.  If I manually stop then start the webjob, it runs through as expected and collects CSP usage properly.

[04/25/2017 09:00:06 > e0802f: INFO] Fetching records for Current Month's Usage from the API. This may take a while. If this operation is timimg out, consider increasing the TimeOut limit in Configuration file. 
[04/25/2017 09:00:06 > e0802f: INFO] 
[04/25/2017 09:00:06 > e0802f: INFO] Error encountered: 
[04/25/2017 09:00:06 > e0802f: INFO] One or more errors occurred.
[04/25/2017 09:00:06 > e0802f: INFO] InnerException :
[04/25/2017 09:00:06 > e0802f: INFO] Exception of type 'Microsoft.Rest.HttpOperationException`1[System.Object]' was thrown.
[04/25/2017 09:00:06 > e0802f: INFO] StackTrace :
[04/25/2017 09:00:06 > e0802f: INFO]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[04/25/2017 09:00:06 > e0802f: INFO]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[04/25/2017 09:00:06 > e0802f: INFO]    at System.Threading.Tasks.Task`1.get_Result()
[04/25/2017 09:00:06 > e0802f: INFO]    at BillingWebJob.Helpers.CspDataHelper.StartCspRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri)
[04/25/2017 09:00:06 > e0802f: INFO]    at BillingWebJob.Program.CronJob(TimerInfo timer) 
[04/25/2017 09:00:06 > e0802f: INFO] 
[04/25/2017 09:00:06 > e0802f: INFO] Adding audit information in AuditData table..
[04/25/2017 09:00:06 > e0802f: INFO] 
[04/25/2017 09:00:06 > e0802f: INFO] 
[04/25/2017 09:00:06 > e0802f: INFO] Operation complete. Exiting this run.
[04/25/2017 09:00:06 > e0802f: INFO] 
[04/25/2017 09:00:06 > e0802f: INFO] Executed: 'Program.CronJob' (Succeeded)

**Comment by jasperkraak** [comment]
@ssugar : this output shows you did not collect any Usage Data. In the AuditData Table you will find just the same exception and no Data in CSPUsage Table.

**Comment by ssugar** [comment]
@jasperkraak  - Yes, that is correct.  What is in my message above is what occurs when I allow the WebJob to run according to it's schedule.  It fails with the same error other people have listed above and no usage data is entered.

If I manually stop and then start the WebJob - which triggers the WebJob to run again, the CSP run completes successfully... not sure why.

**Comment by ssugar** [comment]
@jasperkraak  - Here's the output from a little bit ago after I stopped and started the WebJob:

[04/25/2017 10:19:12 > e0802f: INFO] Starting CSP Routine. Current Usage, Historic Usage and Historic Billing data will be updated.. 
[04/25/2017 10:19:12 > e0802f: INFO] 
[04/25/2017 10:19:12 > e0802f: INFO] Fetching records for Current Month's Usage from the API. This may take a while. If this operation is timimg out, consider increasing the TimeOut limit in Configuration file. 
[04/25/2017 10:22:38 > e0802f: INFO] 
[04/25/2017 10:22:38 > e0802f: INFO] 1570 records fetched from the API.. 
[04/25/2017 10:22:38 > e0802f: INFO] 
[04/25/2017 10:22:38 > e0802f: INFO] All Usage data which exist in DB will be deleted and replaced by new line items.
[04/25/2017 10:22:38 > e0802f: INFO] 
[04/25/2017 10:22:38 > e0802f: INFO] 1567 usage records exist in DB and will be deleted.
[04/25/2017 10:22:41 > e0802f: INFO] 
[04/25/2017 10:22:41 > e0802f: INFO] 1570 new usage records will be added to the database.
[04/25/2017 10:22:44 > e0802f: INFO] 
[04/25/2017 10:22:44 > e0802f: INFO] Now fetching historic usage and billing records from the API month-by-month.

Did you ever get anywhere with the support request you opened?

**Comment by jasperkraak** [comment]
@ssugar I was on vacation for 2 weeks, I send out some info to them yesterday. I will update this thread if we resolve the issue.
By the way, does it work in your situation from the "Swagger" interface? because in my situation that one also generates the failure, so not even the webjob..... but a step before that. I posted the screenclipping in some earlier posts.

**Comment by ssugar** [comment]
In my situation it seems to work via the Swagger UI.  Here's a redacted screenshot of it working just now:
![csprunworking](https://cloud.githubusercontent.com/assets/7929462/25382074/59988f7c-29e0-11e7-91cd-39a992242e82.jpg)

Not sure if it fails intermittently or not via the Swagger UI... For me, the scheduled run of the webjob has failed every day for a few weeks now with the error I listed above, but then a stop/start of the webjob run works well... Clueless as to why at this point.

It does look like during the scheduled runs, the issue occurs when the WebJob calls the WebApi - around line 529 of CspDataHelper.cs in the Helpers folder of the BillingWebJob.  I've enabled some further logging and will try to review tomorrow when the scheduled run fails again.
